### PR TITLE
Input attribute disabled

### PR DESCRIPTION
**Pull request by nrouzaud**
add the disabled attribute on html inputs, which is used in css user-agent-stylesheet

### CODE REVIEW

**Review by livelybone — COMMENTED** [review]
What is the scenario where you use this property？

**Comment by nrouzaud** [comment]
in my app, all inputs fields are greyed out by the css agent style sheet based on this attribute :
image

**Comment by livelybone** [comment]
This is an style problem, I think it is not necessary to add this prop. You can rewrite the agent style instead

**Comment by nrouzaud** [comment]
of course we can, but it doesnt cost to add this in the component, so it is displayed correctly without any configuration with the browser default settings

**Comment by livelybone** [comment]
> of course we can, but it doesnt cost to add this in the component, so it is displayed correctly without any configuration with the browser default setting

I think we just talking about how should the component solve the style problem, I still insist to use the way rewriting CSS outside of the component

**Pull request closed without merging**
